### ISSUE TITLE
File selection in Process1: bug in file filters

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#110]
The code posted here has some issues: https://github.com/brainstorm-tools/brainstorm3/pull/69

Select 2 files, and enter filter "dSPM: MEG(Constr) 2018", it crashes in tree_dependencies>CreateFilterTree (line 852).

**Comment by martcous** [comment]
Fixed in 014c10a5342105eec38c2cd61c52a2b0d82b9645
