### ISSUE TITLE
Add support for reading MFF files

### ISSUE THREAD

**Issue by martcous** [brainstorm-tools/brainstorm3#112]
Use library: https://github.com/arnodelorme/mffmatlabio

Upload big JAR file to NeuroImage server for autodownload.

**Comment by martcous** [comment]
Nevermind, I need to do a lot of custom stuff anyway since with the current API you can only get the header after loading the whole dataset...

**Comment by ftadel** [comment]
Done here: https://github.com/brainstorm-tools/brainstorm3/pull/116

Still missing the basic realignment of the electrodes in our coordinate system.

**Comment by martcous** [comment]
Both remaining items have been added.
