### ISSUE TITLE
Can't open nicolet file for study

### ISSUE THREAD

**Issue by AndreLei** [brainstorm-tools/brainstorm3#124]
Hi there,

could you help me out please. I'm getting an error when trying to import nicolet (.e) file to brainstorm.

![image](https://user-images.githubusercontent.com/1515928/47968052-d33ad600-e064-11e8-947d-5f061402e6fd.png)

Nicolet file for example:
[Patient2_UKCMB_EEG_t1.zip](https://github.com/brainstorm-tools/brainstorm3/files/2546128/Patient2_UKCMB_EEG_t1.zip)

**Comment by martcous** [comment]
The example file you uploaded is working fine on my end. Make sure you unzip it first, and that Brainstorm is up to date.
