### ISSUE TITLE
Spike Field Coherence selects events that are not neurons

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#127]
Follow the e-Phys tutorial to reproduce this issue. After loading the plexon file, import a set of trials (e.g. Stim On 1) and then compute the Spike field coherence on the folder.

The drop-down that selects the neuron after the spike-field-coherence is computed and visualized, should contain only labels that indicate neuronal activity (Spikes Channel AD01). However, other events appear as well (Event001, Event002 ...). This means the "process_spikesorting_supervised('GetChannelOfSpikeEvent', x)" function is producing indices that are not aligned with the events order on the link to raw file events.

**Comment by martcous** [comment]
Fixed in https://github.com/brainstorm-tools/brainstorm3/commit/849f39e3c5edc38f71f5c219ae7ddd19163acf91
