### ISSUE TITLE
Tutorial OMEGA/BIDS

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#143]
Add a review of the literature on resting state MEG.
Download the data from the OMEGA repository.

https://neuroimage.usc.edu/brainstorm/Tutorials/RestingOmega

**Comment by ftadel** [comment]
Still no reference to add for resting state MEG processing?
https://neuroimage.usc.edu/brainstorm/Tutorials/RestingOmega#Resting_state_metrics_.5BTODO.5D

**Comment by sbaillet** [comment]
No forgetting about this but priority is on other fronts given limited resources.

On Nov 9, 2020, at 3:34 AM, Francois <notifications@github.com<mailto:notifications@github.com>> wrote:



Still no reference to add for resting state MEG processing?
https://neuroimage.usc.edu/brainstorm/Tutorials/RestingOmega#Resting_state_metrics_.5BTODO.5D

**Comment by ftadel** [comment]
This is not going to be done any time soon. Closing this issue for now.
