### ISSUE TITLE
file selection in Process1: can't select files that have a time tag.

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#152]
I computed some coherences with a sliding time window (computed coherence multiple times), and added a tag in the end of the COMMENT with the time selection that I used so I can differentiate among files.

However whatever is within the brackets (the added tag) is ignored when I drag n drop it in process 1, so I can't really select the appropriate trials.

The following figure sums it up.
I assume there should be a warning on the File->Add tag function, to not include parentheses, brackets etc. in the comment tag.

![image](https://user-images.githubusercontent.com/23224563/50189140-12aa4280-02f2-11e9-998d-dbdf091849ef.png)

**Comment by martcous** [comment]
This is only an issue for square brackets since it's used for the file counts suffix. I agree, a warning or error should be added to the Add tag process. @ftadel what do you think?

**Comment by mpompolas** [comment]
@martcous can you please take a look at this? I tried to do it myself but couldn't find where the Comment is trimmed once you drop it in the Process1 window.
It took 4 days to compute those coherences and would prefer to avoid computing again.

**Comment by martcous** [comment]
I had a good look as well and I have idea at what point it gets trimmed, maybe in the Java. @ftadel? As soon as you drag it from the DB to the process box it's trimmed.

**Comment by ftadel** [comment]
@mpompolas The Process1 box won't work for file names with brackets. 
You don't need to recompute the files, just replace the square brackets with parathensis.

@martcous You can add warning message in processes "Set comment" and "Add tag": maybe a text message as process option + and error in the Run() function if the user still tries to add brackets.

**Comment by martcous** [comment]
Done in https://github.com/brainstorm-tools/brainstorm3/commit/a2174a1975a6ca21a97d48eb5863a1e2391be603
