### ISSUE TITLE
Kilosort - Change the conversion to Brainstorm events through the bz_GetSpikes

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#156]
A few neurons are assigned to different channels than the bz_GetSpikes function.
Follow what bz_GetSpikes does.

Personal Reminder

**Comment by ftadel** [comment]
Any update on this front?

**Comment by ftadel** [comment]
Any update on this front?

**Comment by mpompolas** [comment]
on it

**Comment by ftadel** [comment]
Fixed in: https://github.com/brainstorm-tools/brainstorm3/pull/516
