### ISSUE TITLE
test_all bad header size for EGI file

### ISSUE THREAD

**Issue by thomas-vincent** [brainstorm-tools/brainstorm3#160]
When running toolbox/script/test_all.m:

```MATLAB
Struct contents reference from a non-struct array object.

Error in test_all (line 272)
hFigRaster = view_erpimage({sFilesEpochs.FileName}, 'erpimage', 'EEG');
```

The [call to Import_data_event](https://github.com/brainstorm-tools/brainstorm3/blob/e58c69fec50d2f523b4647a6dc53efc44644ce90/toolbox/script/test_all.m#L255) cannot find any event so `sFilesEpochs` is empty.

Before that there is a warning while loading "run01.raw":
![image](https://user-images.githubusercontent.com/631566/51202296-6e092980-18cc-11e9-8a55-5639c8fda73f.png)
To which I answered to load the file.

So it seems that the creation of "run01.raw" ([this line](https://github.com/brainstorm-tools/brainstorm3/blob/e58c69fec50d2f523b4647a6dc53efc44644ce90/toolbox/script/test_all.m#L155)) did not go well.

**Comment by ftadel** [comment]
The events bytes were not properly saved in this EGI .raw file in this context.
Fixed in: https://github.com/brainstorm-tools/brainstorm3/commit/8368007c537a371d1dcd2c7c2387bc1aca3dfba9
