### ISSUE TITLE
UltraMegaSort2000 bug with parameters' editing

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#161]
I have a colleague that tried the UltraMegaSort2000 and wanted to edit the parameters:

![image](https://user-images.githubusercontent.com/23224563/51211837-afa5ce80-18e4-11e9-9586-f16964f69443.png)

Once the parameters are edited and OK is pressed, the ss_default_params loses the first line and ultimately leads to an error.

What I mean is, it goes from this:

![image](https://user-images.githubusercontent.com/23224563/51211958-fa274b00-18e4-11e9-85d7-bf193b8cafaa.png)

to this:

![image](https://user-images.githubusercontent.com/23224563/51211963-00b5c280-18e5-11e9-861c-cc56873be3f3.png)

@martcous can you please take a look at this?
Thanks

**Comment by martcous** [comment]
Fixed in 1d07894.
