### ISSUE TITLE
Bugs with the colormap option "Use stat threshold"

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#165]
New option implemented in: https://github.com/brainstorm-tools/brainstorm3/pull/162

Things to be fixed or added:
- 2D/3D topographies: apply different threshold on the values
- Time-frequency maps
- Time-frequency files displayed as 2D/3D topographies
- All types of files displayed with a menu "View as image"

**Comment by thomas-vincent** [comment]
I can have a look at these in March.

For the interpolated map that you showed:
![image](https://user-images.githubusercontent.com/631566/52900948-df3d4480-31ca-11e9-8b21-70cdb3516f03.png)

I guess the behavior is normal since there is some smoothing. I'll try to propose a better representation.

**Comment by ftadel** [comment]
@thomas-vincent 
Please re-open the issue if this is something you still want to work on.
