### ISSUE TITLE
E-phys online tutorials todo-list

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#170]
**Introduction**
_https://neuroimage.usc.edu/brainstorm/e-phys/Introduction_
- Move dataset download to the Brainstorm download page, like all the other files
- Repackage it as .zip (for uniformity)
- The FreeSurfer segmentation looks very weird: ![image](https://user-images.githubusercontent.com/6920058/52286192-0c3a5d80-2968-11e9-80d2-0c37be3b547b.png) 
![image](https://user-images.githubusercontent.com/6920058/52286247-2aa05900-2968-11e9-985a-e6acc6c23511.png)
- The mex files must be built on all the platforms and distributed compiled as part of the Brainstorm distribution. Otherwise most Windows users won't be able to use it, and it wouldn't work in the compiled version of Brainstorm either.  Compiling mex-files on the fly makes the distribution a nightmare, it never works in the same way on two computers.
![image](https://user-images.githubusercontent.com/6920058/52286578-bd40f800-2968-11e9-97ce-daa63f884872.png)
- Crop the screen captures to keep only the interesting information
- Reading data from the .plx seems slow, compared to all the other file formats - has anybody tried to optimize this yet?
- Add the electrode positions: 
  - It is useless in a tutorial to ask people to load a file they don't have. Users should be able to print this page and use it as a manual to reproduce step by step the analysis you suggest on their own recordings. Either you fully teach them how to import/define the electrodes positions, or you don't mention this at all.
  - What you suggest here (loading the channel file from your .rar file) does not work: the positions in this channel file are in SCS coordinates, which depend on the place where the NAS/LPA/RPA points were set. But you don't explain how to place these points, therefore there is very little chance that the probe end up where you want the reader to get it.
  - Asking the users to REPLACE the channel file is not something to advise, as this opens the risk of renaming data channels, in case they are not in the same order. If you want to transfer electrode positions, export them as a text file (right-click > File > Save as file) and then import somewhere else with the menu "Add EEG positions" (instead of "Import channel file")
- Add additional events: 
  - Same comment as for the channel file. If you want a tutorial to be useful, it has to start entirely from raw data, not from data partly processed in an undocumented way. Can't you explain how you converted these events and have the reader redo it? 

**Converting to Brainstorm Events**
_https://neuroimage.usc.edu/brainstorm/e-phys/ConvertToBrainstormEvents_
- I'm not sure this is a good idea to ask people to create these events.mat structures themselves... these are internal structures, subject to change. It would be better to exchange data with other programs using only text files (using one of the existing file format, or creating a new one). This would also avoid the confusion with the redundant .times/.samples information, which we will simplify eventually...

**Spike Sorting in Brainstorm**
https://neuroimage.usc.edu/brainstorm/e-phys/SpikeSorting
- After the introduction tutorial, the folder is called "ytu288c-01", not "ytu288c-01_converted"
- After downloading and installing WavClus, the progress bar is not closed: there is a bst_progress('stop') missing somewhere
- Supervised Kilosort: Options described in the text do not match the screen capture
- Supervised KiloSort: It doesn't work at all without the parallel toolbox? (I could not run it)

**Deriving LFP signals from raw signals**
https://neuroimage.usc.edu/brainstorm/e-phys/RawToLFP
- Could not run it: Function fitLFPpowerSpectrum.m calls lsqnonlin.m, which is part of the optimization toolbox. This is not such a common toolbox. It looks like there is an Octave version available (https://octave.sourceforge.io/optim/package_doc/lsqnonlin.html) anybody interested in porting it to Matlab and adapt the function accordingly? (like it was done with all the other oc_*.m functions in Brainstorm)

**Spike triggered average**
https://neuroimage.usc.edu/brainstorm/e-phys/functions#Spike_triggered_Average
- The implementation of the 2DLayout changed a lot since you did this screen capture... To avoid having the display depending on the orientation of the probe, now it flattens the view:
![image](https://user-images.githubusercontent.com/6920058/52295886-34808700-297d-11e9-9a67-cdd90480b457.png)

**Comment by ftadel** [comment]
@mpompolas @martcous @sbaillet 

I'm not sure if any of there serious issues were ever addressed.
Will someone work on this at some point?

**Comment by ftadel** [comment]
@mpompolas @sbaillet 
These issues make the entire ephys tutorials very difficult to follow.

**Comment by mpompolas** [comment]
Started working on it

**Comment by mpompolas** [comment]
Continuing the updates on: https://github.com/brainstorm-tools/brainstorm3/issues/387
