### ISSUE TITLE
File selection in Process1: added time tags selection doesn't differentiate between positive and negative values

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#172]
Came across this weird selection from the filter selection. 
I added some tags (-350, 0) and (0,350) ms on my files.

When I try to make the selection with the filter based on the "**Search Comments**" field and add **(0, 350)**, it selects BOTH which is problematic:
![image](https://user-images.githubusercontent.com/23224563/52377191-250f4580-2a32-11e9-9f95-6733fa6acd1f.png)

If I add the negative time selection in the filter: **(-350, 0)** it works fine:
![image](https://user-images.githubusercontent.com/23224563/52377298-73244900-2a32-11e9-857c-7bb8a3f5a9d5.png)

**Comment by martcous** [comment]
The Comment Filter works with boolean logic, which includes reserved characters such as parentheses, and/&/&& and or/|/||. If you want to include a reserved character in your search without making use of the boolean logic operators, add strings to your query. In this case, "(0, 350)" would work properly and only select your first file.

**Comment by mpompolas** [comment]
This is neat. Didn't even know there was a boolean filter.
I assume it was on the latest updates.

Either way, thanks
