### ISSUE TITLE
Minimum iEEG tab values should be lower

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#208]
The minimum values that can be set within the iEEG window for electrode metadata (electrode diameter, contact diameter etc.) seems to be 0.1 mm.

I got contacted by some mice people that want to use Neuropixels:
http://www.open-ephys.org/neuropixels

The selling point of these electrodes is how insanely dense they are (1000 channels within 10mm length and 70 micron width).

Can we lower these minimum values?

**Comment by ftadel** [comment]
Done in https://github.com/brainstorm-tools/brainstorm3/commit/93cbe223161746b2fadc14e46062014d590725bb#diff-5d03d3ef5441acf005318a4a8bd366b4

You can go down to 0.01, and therefore enter your 70microns length.
If this is OK with you, please close this issue.

**Comment by mpompolas** [comment]
Yes, each column is 0.016 mm apart according to the attached figure, so we're good.

![neuropixel](https://user-images.githubusercontent.com/23224563/58195392-d8c0dc00-7c95-11e9-99ab-9f8c9ed47eb7.png)

**Comment by mpompolas** [comment]
extension of this problem when trying to assign:
Set tip
Set skull 
entries on a mouse.

![image](https://user-images.githubusercontent.com/23224563/58668735-d1d64100-8307-11e9-86c4-cb7affee1605.png)

**Comment by ftadel** [comment]
I lowered the distance check to 2mm.
Is that OK?

**Comment by mpompolas** [comment]
It appears to be ok,
Thanks
