### ISSUE TITLE
Old event files fail to load after the addition of channels, notes

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#214]
Just got an email from someone who wanted to use the tutorial dataset for the invasive neurophysiology toolbox.

On that dataset I have an extra file with events that (since it was created in November) doesn't have the channels and notes fields.
When he tried to import he got an error that there is no channels field:
![Brainstorm_e-Phys error](https://user-images.githubusercontent.com/23224563/58653258-4f3b8a80-82e3-11e9-80c4-9805eba734af.jpg)

I updated the tutorial file to accomodate the changes, but for backwards compatibility there should be a check if the files that are getting imported are with the old format.

**Comment by martcous** [comment]
Fixed in https://github.com/brainstorm-tools/brainstorm3/commit/8d967131591c1e09fefb40e03a8c3bc6ae1fd6c1
