### ISSUE TITLE
New decoding processes: do not work in older Matlab versions + documentation

### ISSUE THREAD

**Issue by martcous** [brainstorm-tools/brainstorm3#215]
For example, it does not run on Matlab versions before R2014b: missing function histcounts() used in the scilearnlab library. Either see if such instances can be replaced or add warning to process.

**Comment by ftadel** [comment]
Wasn't someone supposed to write a tutorial for these new processes?

**Comment by ftadel** [comment]
?

**Comment by ftadel** [comment]
Added an error if Matlab < 2014b:
https://github.com/brainstorm-tools/brainstorm3/commit/82c9d47d17ba1de5b57dc31846265e9c66224c63
