### ISSUE TITLE
Raster plot visualization needs some adjustment

### ISSUE THREAD

**Issue by mpompolas** [brainstorm-tools/brainstorm3#221]
The raster plot shows the spiking activity of each neuron.  There is a problem though with the visualization of this activity. 
Since the raster plots are not binned (no temporal smoothing), the x-axis (time dimension) is a much larger vector than the y-axis (number of trials). This creates a rendering problem when the figure is scaled, as shown on the next two figures:

![image](https://user-images.githubusercontent.com/23224563/59953464-3475b500-944e-11e9-8c2e-9eec27d10801.png)

![image](https://user-images.githubusercontent.com/23224563/59953470-38a1d280-944e-11e9-9f57-cffa9771d70b.png)

Maybe a visualization with dots would be appropriate?

**Comment by ftadel** [comment]
Probably. 
Dots can be created with the function line. Example:
```
line(X, Y, Z, 
   'Color', [1 0 0], ...
   'LineStyle', 'none', ...
   'Marker', '.', ...
   'MarkerSize', 1, ...
   'Parent', hAxes);
```

**Comment by mpompolas** [comment]
@martcous can you please take a look at this?
If I'm not mistaken, figure_timefreq is the function that needs to be modified to show dots instead of weird lines. 

Here is an example raster file: 
https://www.dropbox.com/s/6mewjk8stfdm9z5/rasterplot_problematic.mat?dl=0

Thanks

**Comment by ftadel** [comment]
If you really need to display dots instead of an image, you guys should maybe think about writing a new figure function? The time-freq plane is not useful at all in this case

**Comment by martcous** [comment]
The time-frequency is useful in the sense that it gives us the dropdown interface to choose which electrode to display in the Display tab:
![image](https://user-images.githubusercontent.com/9253273/60189268-a0fe0480-97fe-11e9-9e36-43f264d924cf.png)

I will need to be pointed in the right direction if you want me to write an entirely new figure function. To me it sounds like a lot of work rather than a simple if/else condition in the time-freq display function.

**Comment by ftadel** [comment]
Up to you, if you already have a solution in mind that would satisfy Konstantinos, go for it!
It's not like if we were developing a super clean structure around these time-frequency objects anyway :)
(eg. connectivity matrices and PAC results squeezed-in not-so-gracefully)

**Comment by mpompolas** [comment]
Just did a very quick search. This tool might do the trick. Not sure how easy it is to implement within the interactive windows, but it would be a start:

https://www.mathworks.com/matlabcentral/fileexchange/45671-flexible-and-fast-spike-raster-plotting

**Comment by martcous** [comment]
Fixed in https://github.com/brainstorm-tools/brainstorm3/commit/65c283cb246e8e70c26b0576985ea78e55dbbf0f

![image](https://user-images.githubusercontent.com/9253273/60618005-ff992480-9da2-11e9-870e-6c78621e0f8d.png)

**Comment by mpompolas** [comment]
Just checked the rasterplot. It is a bit sparse on my display. It only shows patterns when I make my window very small.
Can you please make the dots a bit bigger @martcous ?
Thanks

**Comment by martcous** [comment]
Sure, I increased the dot size. I also properly implemented the "All Channels" display so that you can view a low resolution snapshot of all channels at once. It's definitely not perfect since these are small dots so a lot are lost with downsizing, but it already gives you an idea of which channels have more than others.

![image](https://user-images.githubusercontent.com/9253273/60738705-42870380-9f2d-11e9-82a1-0956bcd162ad.png)

**Comment by mpompolas** [comment]
this is actually neat.
I wanted to be able to display several neurons simultaneuously but I thought it would be an overkill to implement.

It's great you did it. The only comment I would make, is to present the 2d rasterplots from all neurons, on the same column (instead of a 3x4 subplot that you have, make it a 12x1). This way it should show the temporal selectivity of the neurons more appropriately.

This would be a problem if we have too many neurons though. Is it possible to select a few neurons (like a montage) instead of all of them?

Something like the way fieldtrip is set:

![05-07-2019 14-05-14](https://user-images.githubusercontent.com/23224563/60739105-92b29580-9f2e-11e9-90e7-1f666b6bb3d0.png)

**Comment by martcous** [comment]
Maybe in version 3.0! ;)

**Comment by ftadel** [comment]
@mpompolas @martcous 
Do you want to keep this issue open?

**Comment by mpompolas** [comment]
This is not something anyone is working on at this point, so I would say we close it and revisit it if ever needed.
