### ISSUE TITLE
Line display for cardiac events creates full page vertical lines

### ISSUE THREAD

**Issue by jeremymoreau** [brainstorm-tools/brainstorm3#223]
I've been using the new "Lines" display option for events (which is great for spikes btw!), but it creates distracting full page lines for cardiac events for some reason. In the "Dots" view these non-channel events show up as dots at the top of the page, which is the expected behaviour. See screenshots below.

![cardiac_lines_events](https://user-images.githubusercontent.com/7446564/60355901-8d3cd480-999d-11e9-8251-c620a2c6b975.png)
![cardiac_dots_events](https://user-images.githubusercontent.com/7446564/60355909-929a1f00-999d-11e9-89df-a0df99209e54.png)

**Comment by ftadel** [comment]
No, I actually intended it this way: in the "lines" mode, all the events are displayed as lines. This is useful as well for people who do not use channel events, or can be used to highlight some pars of an ERP for instance:
https://neuroimage.usc.edu/brainstorm/Tutorials/EventMarkers#Display_modes

Indeed, the cardiac events can be very annoying in this mode.
This is why I also added an option to mute some event groups (easy toggle with shortcut key H):
https://neuroimage.usc.edu/brainstorm/Tutorials/EventMarkers#Hide_event_groups

**Comment by ftadel** [comment]
(I closed it, but please reopen if you think I really need to fix something here)

**Comment by jeremymoreau** [comment]
No, I agree with you. I can see this being useful for some people. I wasn't aware of the hide event groups option, that's awesome! Thanks!
