### ISSUE TITLE
Page setting when displaying Nirs time series

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#226]
Hello,

I am contacting you because, when displaying Nirs data, it's seems that it is not possible to use the Page setting panel to navigate easily through the data.   

![Screenshot - 19-07-26 - 01:50:05 PM](https://user-images.githubusercontent.com/24530402/61971548-56aea580-afad-11e9-8c0b-a8c2da49ca3e.png)

thx

**Comment by ftadel** [comment]
This is related with the way you imported your recordings in the database.
When reviewing continuous recordings, you have access to these options.
When opening imported blocks of recordings, you don't.
https://neuroimage.usc.edu/brainstorm/Tutorials/ChannelFile#Review_vs_Import
