### ISSUE TITLE
Keyboard Shortcut triggered while renaming a node and events tab is active. 

### ISSUE THREAD

**Issue by juangpc** [brainstorm-tools/brainstorm3#236]
Hi all,
Just came upon a small bug that might get some users confused. Maybe it is just too rare and thus it doesn't deserve a fix. But just in case.

If you are changing the name of a node and the event window is active, then the FigureKeyPressedCallback is called whenever a matching letter shortcut is typed, even while renaming a node.

Context: 
1. Open a protocol.  
2. Double click on any time-series of this study.
3. Select the "Record" tab so that the events are visible.
4. Go back to the study and try to rename a recording. For instance, select a recording and press F2. 
5. If you enter a name containing the letter 'e', for instance, at that point, the key press 'e' will trigger --> new event. And later generating an exception because no event group is selected.

Maybe it would make sense to make the FigureKeyPressedCallback process the keyboard input only if the time-series window is selected/active? Or perhaps, when renaming is taking place, disable the keyPressed callback? Or maybe it is too rare. Either way, I would like to know what you guys think.

Thanks,

**Comment by ftadel** [comment]
Good catch!
I've added a fix to make sure the accelerator keys for the menus in the tab "Record" are not used when editing text. I'm testing only the renaming in the tree and the search box at the bottom-right corner. Let me know if you find other configurations in which these menus are called when the should not.
https://github.com/brainstorm-tools/brainstorm3/commit/048120dc682bee29a37fff99f38e3f9ac8508827

**Comment by juangpc** [comment]
Thanks. But I wish I would have been able to propose a solution. At least I can follow yours.
