### ISSUE TITLE
Color map for single channel NIRS time course

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#253]
Hi there,

I was plotting the time course of a single channel NIRS by selecting it from the plot of all channels and hit enter. The image was plotted well but the colormap could be better or consistent with the all-channel plot (eg HbO in red, HbR in blue and HbT in green). It is the case when we plot all of the channels but not when we only show one channel. 

![exe;ple](https://user-images.githubusercontent.com/24530402/73303096-c400f480-41e3-11ea-8391-38bad0501d3c.png)

Do you think it is easy to fix? 
Thank you :)

**Comment by ftadel** [comment]
Sorry, I missed this post... I'll have a look at it soon.

**Comment by ftadel** [comment]
Would this simple fix work for you ?
https://github.com/brainstorm-tools/brainstorm3/commit/c7108fc9e22d7f5464e7f985390e53747ee13a0c

If it does, please close the issue.

**Comment by Edouard2laire** [comment]
yes, that's great ! 
Thank you
