### ISSUE TITLE
Fixing buggy figure export

### ISSUE THREAD

**Issue by d-arzounian** [brainstorm-tools/brainstorm3#268]
I noticed an error when trying to save a figure in FIG format from a script and looked into the code.

https://github.com/brainstorm-tools/brainstorm3/blob/71158e41ced707ac27db0bcb0c9c5bb67d2198db/toolbox/io/out_figure_image.m#L89

I believe the above-quoted line should rather be:
`if ~isempty(fExt)`

**Comment by martcous** [comment]
Thank you for the report! Fixed: https://github.com/brainstorm-tools/brainstorm3/commit/8646eeb24e99d107ba36cbfe520364c15a8a0bde
