### ISSUE TITLE
OpenMEEG update install menu bug

### ISSUE THREAD

**Issue by Moo-Marc** [brainstorm-tools/brainstorm3#276]
I was trying to use Brainstorm to change my OpenMEEG version (for testing stuff), but nothing was happening.  in bst_openmeeg, line 111, if AutoUpdates is off and prevUrl is not empty, not only the download, but also the actual installation starting at line 149 are skipped.  Maybe some if blocks got mixed up?

**Comment by ftadel** [comment]
fixed: 
https://github.com/brainstorm-tools/brainstorm3/commit/14f755658a625a2ef40ce552eff4ffd18f665fcc
