### ISSUE TITLE
Process for Headmodel files (within process boxes)

### ISSUE THREAD

**Issue by tmedani** [brainstorm-tools/brainstorm3#298]
Hello, 

Following our previous discussions,  in this thread, we may discuss how we can add the possibilities to 'drop and drag' the headmodel files on the process boxes and also which metrics/methods to use in order to compare between headmodels. 

For now, the only way to compare between headmodels is to display the leadfield vectors. 

There are two main steps : 
- 1 - add the possibility to process headmodels files
- 2 - add methods to compare/process the headmodels files  

Thanks

**Comment by ftadel** [comment]
Handling headmodel files in the Process1/Process2 tab would require a substantial amount of work for a very limited usage.
I suggest we handle this directly from the database explorer: select two head models, right-click > **Compare leadfields**.
I'll try to work on this soon.
