### ISSUE TITLE
Failed to Generate Head Surface (Histogram failure)

### ISSUE THREAD

**Issue by bjbalken** [brainstorm-tools/brainstorm3#312]
For detailed report see:
https://neuroimage.usc.edu/forums/t/brainstorm-generate-head-surface-fails/20166/4

The root of the problem turned out to be in mri_histogram on line 231 where the function is attempting to determine if the background has been removed in the MRI. In our case, we DO remove the background during a cleaning step. It was failing to recognize this. I changed the conditional statement on line 231 to the following (and now everything is working for us):

( ((nzero(1)>2) && ~isempty(nnonzero) && (nnonzero(1) > nzero(1))) || (Histogram.fncY(1) == max(Histogram.fncY)) )

because there are more zero value voxels in our MRIs than nonzero. This is a fairly safe assumption for our data because our zero voxels are over 3x as numerous as nonzero. However, brainstorm devs might want to take a closer look at the mri_histogram function in general. I also noticed an unsafe assumption on lines 240-250 where it assumes "if the highest maxima is > (3*second highest maxima) : it is a background maxima : use the first minima after the background maxima as background threshold". This is where our histogram was failing (see detailed report for visualization). It didn't recognize that the background was removed so it continued on to attempt to use this assumption to determine the bgLevel but that wasn't accurate for our data.

We are using MP2Rage images that have had their static removed. See example below.

![image](https://user-images.githubusercontent.com/29381284/86780318-9fc70080-c02a-11ea-8fb9-3d278fe91561.png)

Before static is removed:
![image](https://user-images.githubusercontent.com/29381284/86780400-b705ee00-c02a-11ea-9e94-503b0adaff40.png)

**Comment by ftadel** [comment]
Moved this post to the discussion that was already started on the forum, to avoid having the same discussion in multiple places:
https://neuroimage.usc.edu/forums/t/brainstorm-generate-head-surface-fails/20166/9?u=francois
