### ISSUE TITLE
CS convert for headreco output oversizes the mesh in some direction

### ISSUE THREAD

**Issue by tmedani** [brainstorm-tools/brainstorm3#328]
Hello,

New strange behavior of the cs_convert in this specific case with the  SimNibs mesh output, 

Here is the case, I'm using the MRI from the BrainSuite tutorial, run the SimNibs for mesh generation, and get the head model. 

Here is the result

![image](https://user-images.githubusercontent.com/37831900/91346951-6e4ef380-e796-11ea-8636-99f89bc47b05.png)

![image](https://user-images.githubusercontent.com/37831900/91346958-7313a780-e796-11ea-8807-df001b4d6985.png)

The mesh is oversized in some direction compare to the input MRI, and to the tissue. 

After some investigations,  all the MRI and the tissues are correct and well-aligned
![image](https://user-images.githubusercontent.com/37831900/91347976-f8e42280-e797-11ea-9d64-f86d24c8536c.png)

The original mesh output from SimNibs also looks correct, 

![image](https://user-images.githubusercontent.com/37831900/91348091-24670d00-e798-11ea-9982-4b0a14eb661a.png)

 
It seems that the error is occurred at the step of the coordinate system conversion, 

![image](https://user-images.githubusercontent.com/37831900/91348273-62643100-e798-11ea-8300-266b782ea5b0.png)

https://github.com/brainstorm-tools/brainstorm3/blob/f81bda70c9ebad55d5b5ba8d472f2c054936e5ea/toolbox/io/in_tess.m#L190

Here is the output of these lines, 

![image](https://user-images.githubusercontent.com/37831900/91348635-ec13fe80-e798-11ea-8e78-ea2f1c74eb34.png)

The problem is mainly at this line 
            TessMat.Vertices = cs_convert(sMri, 'voxel', 'mri', TessMat.Vertices);

I think the problem comes from the voxelsize, =    [1.33, 1, 1], 

I don't have a solution right now without changing the core function of the cs_convert. 

But, maybe a general solution is to reslice the initial MRI to an isotropic voxel and then call headreco?

In case, where someone wants to reproduce this issue, here is the link to the sMRI and the TessMat : https://drive.google.com/open?id=1mLJ3zfzFZFL5_K-XQGWPK-u_cdj0Tl6x&authuser=medani%40usc.edu&usp=drive_fs

**Comment by ftadel** [comment]
It is not a problem with cs_convert, it is a problem with the import of the SIMNIBS outputs.
What it means is that the vertices of the mesh read from the .msh files are not in "voxel coordinates".
The line `TessMat.Vertices = cs_convert(sMri, 'voxel', 'mri', TessMat.Vertices);` multiplies the coordinates with sMRI.Voxelsize and divides by 1000. It has to be replaced with something else, maybe only a division by 1000.

You can probably easily fix this. Check that it works on a few MRI with different voxel sizes.

**Comment by tmedani** [comment]
> The line `TessMat.Vertices = cs_convert(sMri, 'voxel', 'mri', TessMat.Vertices);` multiplies the coordinates with sMRI.Voxelsize and divides by 1000. It has to be replaced with something else, maybe only a division by 1000.
> 
> You can probably easily fix this. Check that it works on a few MRI with different voxel sizes.

I think so, it does not require the multiplication by the Voxelsize, 

I will check it, but it need time to validate it in some MRI.

**Comment by ftadel** [comment]
Let me know if it works to replace the line
`TessMat.Vertices = cs_convert(sMri, 'voxel', 'mri', TessMat.Vertices);`
with:
`TessMat.Vertices = TessMat.Vertices ./ 1000;`

I will commit the change after you validate with a volume with a voxel size different from [1,1,1].

**Comment by tmedani** [comment]
Hi @ftadel 
I check in some MRI (4 subjects)  with different voxel size, and the error comes from the 

cs_convert(sMri, 'voxel', 'mri', TessMat.Vertices)

please just replace it 
> with:
> `TessMat.Vertices = TessMat.Vertices ./ 1000;`

It solves the problem, 

However, I don't understand why the 0.5 voxel correction in line 194,
I do not notice any visual difference with and without it.
Is there any reason for adding it?  @juangpc

**Comment by ftadel** [comment]
>please just replace it

Done: https://github.com/brainstorm-tools/brainstorm3/commit/a864cce53a4e7fa65688234c1decfc7c75b433a7

> However, I don't understand why the 0.5 voxel correction in line 194,

Probably a different in the convention of where the center of the first voxel is: (0,0,0) or (0.5,0.5,0.5) ?

**Comment by tmedani** [comment]
> > please just replace it
> 
> Done: [a864cce](https://github.com/brainstorm-tools/brainstorm3/commit/a864cce53a4e7fa65688234c1decfc7c75b433a7)

super, thanks.


> > However, I don't understand why the 0.5 voxel correction in line 194,
> 
> Probably a different in the convention of where the center of the first voxel is: (0,0,0) or (0.5,0.5,0.5) ?

If I understand well, in this case, we move the whole head by (0.5/1000) mm ?
which seems to be insignificant.
