### ISSUE TITLE
About birainstrom's bandpass filter

### ISSUE THREAD

**Issue by pengweimin** [brainstorm-tools/brainstorm3#369]
Hello, we use brainstorm on matlab to perform band-pass filtering. How can I reproduce the same program on python?

**Comment by ftadel** [comment]
The specification of the filters is available here:
https://neuroimage.usc.edu/brainstorm/Tutorials/ArtifactsFilter#Filter_specifications:_Low-pass.2C_high-pass.2C_band-pass
The interactive interface reports many properties of the filter.

The code is available here:
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/math/bst_bandpass_hfilter.m
Obtaining the same results in Python would probably require a full recoding of this function in Python.
