### ISSUE TITLE
MRI Coordinates values on the bst MRI viewer 

### ISSUE THREAD

**Issue by tmedani** [brainstorm-tools/brainstorm3#381]
Hi @ftadel 

I have just noticed that the MRI coordinate displayed on the top of the MRI are different from those displayed on the table. 

![image](https://user-images.githubusercontent.com/37831900/107445134-bbc6df00-6af0-11eb-982a-990410dda3fb.png)

It seems that the values on the top are correct. 

best,

**Comment by rcassani** [comment]
Hi @tmedani, I'm using the 08-Feb-2021 version and the coordinates in the figures and the table agree in the MRI Viewer.

**Comment by ftadel** [comment]
Above the slices: this is the slice index in the volume.
In the Coordinates panel, this are coordinates in millimeters.
You have the same values only if the voxel size is 1x1x1mm.

**Comment by tmedani** [comment]
Thanks, @ftadel  & @rcassani,

Indeed, my MRI is not wired in this example, I miss to check it.

thank you
