### ISSUE TITLE
Consider a cloud CI service

### ISSUE THREAD

**Issue by acampbel** [brainstorm-tools/brainstorm3#409]
Given public open source projects have free support for cloud ci services, consider leveraging one of them here. 🎉

https://blogs.mathworks.com/developer/2020/12/15/cloud-ci-services/

**Comment by ftadel** [comment]
Thank you for the suggestion.
Unfortunately we are not at this stage evolution yet, we are still living on a 20yr code base with no unit tests...
Hopefully we'll get the necessary funds to hire someone for setting up a proper testing framework at some point.
