### ISSUE TITLE
OpenMEEG migration heads up

### ISSUE THREAD

**Issue by papadop** [brainstorm-tools/brainstorm3#439]
This is just a head's up message for now.

The old INRIA forge (gforge) will close soon (they say us the end of the month, probably to push for the migration).
Consequently, we will have to migrate the OpenMEEG binary files that brainstorm uses to a new place called files.inria.fr.

Consequently, the web adress "http://openmeeg.gforge.inria.fr/download/" mentioned several times in brainstorm sources will have to change sooner or later (and the sooner, the better). I will try to ask for a redirection so that not to break installed brainstorms. 

I will communicate the new URL here as soon as I will obtain the new one and have copied files from the old repository to the new one.

Sorry for the disturbance....

**Comment by ftadel** [comment]
Thank you for the notice.
Please keep us posted when you have the new download URLs.

**Comment by ftadel** [comment]
The download URLs are not valid anymore, there are no redirections set up, and we didn't receive the updated URLs yet...
Can you please help us with that?

**Comment by ftadel** [comment]
https://neuroimage.usc.edu/forums/t/where-to-get-openmeeg-precompiled-binaries-problems-installing-it-from-matlab/30869/2

**Comment by papadop** [comment]
Normally, things should now work with the URL: 
https://files.inria.fr/OpenMEEG/download/
This can replace the old URL in the brainstorm code. It will not break old code because there is a redirection from the old URL to the new one.

**Comment by ftadel** [comment]
> Normally, things should now work with the URL:

URLs updated: https://github.com/brainstorm-tools/brainstorm3/commit/2f85368f32e38182964adf594e8ccdea6d01b107

> It will not break old code because there is a redirection from the old URL to the new one.

http://openmeeg.gforge.inria.fr/download/OpenMEEG-2.4.1-Linux.tar.gz redirects to https://openmeeg.github.io/
Not to: https://files.inria.fr/OpenMEEG/download/OpenMEEG-2.4.1-Linux.tar.gz

Therefore it does break the existing code...
Am I missing something?

**Comment by papadop** [comment]
I have passed the information to our administrators...
Unfortunately, I do not have the hand on the problem.

**Comment by agramfort** [comment]
thanks @ftadel for having updated the URLs in the source files 🙏

**Comment by ftadel** [comment]
Ok, people will have to update Brainstorm before updating OpenMEEG.
That works too...
