### ISSUE TITLE
Manual alignment does not support the FEM objects

### ISSUE THREAD

**Issue by tmedani** [brainstorm-tools/brainstorm3#452]
Hi @ftadel,

I tried to use the "Manual alignment on ..." option to align surfaces interactively with the GUI, 
however, the current version does not support the FEM models. 

Is it straightforward to add it? 

Thanks 

Takfarinas

**Comment by ftadel** [comment]
Done: https://github.com/brainstorm-tools/brainstorm3/commit/0cad251a310bee76ec448af78a2936bc4a255aba

**Comment by tmedani** [comment]
Awesome, will test it and share feedback

thank you, Francois.
