### ISSUE TITLE
Deleting subject when sorting the files by condition

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#454]
hello, 
This is not really a bug I am reporting but behavior that I think might be very misleading in brainstorm ( accidentally delated a lot of data because of that...)

When looking at the DB using the sort by condition 9see picture) if you are selecting a subject under a specific condition (lets say MA') and deleting it, the 'obvious' behavior is to delete the condition MA for the subject but what is happening is that its deleting the entire subject from the database.
![ex1](https://user-images.githubusercontent.com/24530402/140621521-eeb860cf-a759-4837-abc1-ffc113118110.png)

After review, I agree that Brainstorm is saying 'Do you want to delete the *subject*, but I think more warning should be put here as it's not obvious, when tired, that it will completely delete the subject and not just the condition in the subject because if you click on a condition and delete it it's deleting the condition for all subject so if clicking on a subject within a condition you would expect it to delete fewer files... 

Edouard

**Comment by ftadel** [comment]
You are right.
I disabled it completely: https://github.com/brainstorm-tools/brainstorm3/commit/89a28d54ae0504375f4fff372be72dd39d4f4f52
