### ISSUE TITLE
bdf file input error

### ISSUE THREAD

**Issue by micuat** [brainstorm-tools/brainstorm3#47]
it seems this line has a problem:
https://github.com/brainstorm-tools/brainstorm3/blob/8e2c9506d2f1e3b67c8f7382e7cc3141da3b7a46/toolbox/io/in_fopen.m#L86

It should be

    case {'EEG-EDF', 'EEG-BDF'}

to load bdf properly.

**Comment by ftadel** [comment]
Of course!
That's a typo from code manipulation from the last days.
Fixed: https://github.com/brainstorm-tools/brainstorm3/commit/e8dd75f30ac932dcf8ce6d0dcd97dbcac14394bb
