### ISSUE TITLE
Sgmenting MRI - Brainstorm is not keeping the right MRI

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#485]
Hello, 

if you try to segment subject anatomy with multiple MRIs, brainstorm will delete all MRIs except the one named MRI (and not keep the one selected as default MRI). 

To reproduce; import an MRI; resample it; try to launch cat12 on the resampled MRI. It will delete the file and then crash

Edouard

**Comment by ftadel** [comment]
Addressed here:
https://github.com/brainstorm-tools/brainstorm3/commit/c9cb9f4c35ab39e1ef4df55e00469eda94f55892
https://github.com/brainstorm-tools/brainstorm3/commit/2d13b755aaf24d6b8c8a7871475dc87e838115e9
