### ISSUE TITLE
Error importing FastSurfer folder

### ISSUE THREAD

**Issue by alx080** [brainstorm-tools/brainstorm3#528]
Hello,
in your tutorial for [FastSurfer](https://neuroimage.usc.edu/brainstorm/Tutorials/SegFastSurfer) it is written that you can import the FastSurfer folder as illustrated in the FreeSurfer tutorial, but I get this error:

<img width="1505" alt="err" src="https://user-images.githubusercontent.com/95551024/159743365-859d7280-5823-46d5-9629-20416e481334.png">

Is there a way to fix this?

**Comment by ftadel** [comment]
Can you please share an example for us to reproduce the error?
- Duplicate the FastSurfer folder
- In the copy, delete all the files except needed by Brainstorm (listed here: https://neuroimage.usc.edu/brainstorm/Tutorials/LabelFreeSurfer#Files_imported)
- Make sure you still get the same error when trying to import this folder (make sure it's the same error message, not simply an error). If you get a different error: Keep the entire initial folder. It was just to save some space in the file transfer...
- Zip the folder
- Upload the .zip file somewhere
- Post the download link here
- 
Thanks

**Comment by alx080** [comment]
It was the same error, also this time I used the example MRI from FastSurfer's [Google Colab](https://colab.research.google.com/github/Deep-MI/FastSurfer/blob/master/Tutorial/Complete_FastSurfer_Tutorial.ipynb).
Here is the folder: [Link](https://drive.google.com/file/d/1D-BKy2LO2ASgJ2HyqXTRe24-DWSkco8w/view?usp=sharing)

**Comment by ftadel** [comment]
The files `lh.white` and `rh.white` are empty: something went wrong either during the FastSurfer computation, or during the copy of the results (e.g. you copied the output folder with a tool that can't handle symbolic links).

Two solutions:
- You fix the `white` surfaces from the input folder
- You simply delete them (everything else will work):
![image](https://user-images.githubusercontent.com/6920058/160078295-68ef3961-6360-4b08-969f-fe1af7373d79.png)
![image](https://user-images.githubusercontent.com/6920058/160078314-e6c73447-fa37-4daa-b59a-c1965fa49e10.png)
