### ISSUE TITLE
To check: repmat iA and iB vs HA and HB directly

### ISSUE THREAD

**Issue by danielemarinazzo** [brainstorm-tools/brainstorm3#561]
Hi

For some dimensions of HA and HB, it's faster to repmat/repelem the matrices directly rather than the indices.
You can play with the dimensions in the scripts below. 

```
regions=round(logspace(1,3,25));T=round(logspace(2,3,20));
timediff=zeros(length(regions),length(T));
for ireg=1:length(regions)
    for it=1:length(T)
        HA=ones(regions(ireg),T(it));HB=HA;
        [nA,nT]=size(HA);
        [nB,nT]=size(HB);
        
        tic
        iA = repmat(1:nA, 1, nB);
        iB = reshape(repmat(1:nB, nA, 1), [], 1);
        foo=HA(iA,:)./HB(iB,:);
        t1=toc;
        
        
        tic
        foo=repmat(HA,[1 nA])./repelem(HB,1, nA);
        t2=toc;
        timediff(ireg,it)=t1-t2;
    end
end
```
![repmat_alltoall](https://user-images.githubusercontent.com/5311102/179371658-27f0d9de-df99-4507-9e7b-4c86b4369df3.png)

```
regions=round(logspace(1,5,25));T=round(logspace(2,4,20));
timediff=zeros(length(regions),length(T));
for ireg=1:length(regions)
    for it=1:length(T)
        HA=ones(1,T(it));HB=ones(regions(ireg),T(it));
        [nA,nT]=size(HA);
        [nB,nT]=size(HB);
        
        tic
        iA = repmat(1:nA, 1, nB);
        iB = reshape(repmat(1:nB, nA, 1), [], 1);
        foo=HA(iA,:)./HB(iB,:);
        t1=toc;
        
        
        tic
        foo=repmat(HA,[1 nA])./repelem(HB,1, nA);
        t2=toc;
        timediff(ireg,it)=t1-t2;
    end
end
```
![repmat_onetoall](https://user-images.githubusercontent.com/5311102/179373897-658f6cf0-cfdb-424f-935b-fd4182cda599.png)

**Comment by ftadel** [comment]
Thank you for exploring the optimization options for this script!

Unfortunately, I don't think we will have time to play with these parameters ourselves anytime soon.
If you think there are some significant improvements that can be achieved (e.g. more significant than a 10% duration decrease in rare use cases), please open a PR with the suggested modifications.
