### ISSUE TITLE
toolbox/gui/view_connect.m Implementation

### ISSUE THREAD

**Issue by Navaneethmak** [brainstorm-tools/brainstorm3#592]
The toolbox zeros the diagonals while plotting however, the original matrix in db retains the diagonals.
Need to explicitly mention this to user to avoid errors.

**Comment by rcassani** [comment]
Zeroing the diagonal elements is proposed as an option in #553.
Additional information can be found in Brainstorm connectivity tutorial: 
https://neuroimage.usc.edu/brainstorm/Tutorials/Connectivity#Result_visualization

**Comment by rcassani** [comment]
Solved at dd6a2cdc1fd7412aa9ef2bb6d8aa82c6905c6353

**Comment by ftadel** [comment]
Some cases are not handled correctly. See PR.

**Comment by ftadel** [comment]
Finally addressed here: 
https://github.com/brainstorm-tools/brainstorm3/pull/596
