### ISSUE TITLE
EDF export creates files with wrong amplitudes

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#61]
Link an EDF file to the database, import a block of 1s from it, export  this block to an EDF file, import it again.
The amplitudes of the files in input and output are completely different...
[p45_cw-export.zip](https://github.com/brainstorm-tools/brainstorm3/files/1710583/p45_cw-export.zip)

**Comment by martcous** [comment]
There were multiple issues with the EDF export, I _think_ fcdaccc706545309a4bde930186a85278bb8fd1c fixes all of them.

**Comment by ftadel** [comment]
I've tested it on a few files, it looks like it's working great.
Thanks!
