### ISSUE TITLE
Process -  working with continuous recording

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#630]
Hello, 

A few months ago I worked on a process to synchronize two files https://github.com/brainstorm-tools/brainstorm3/pull/397 and it was rejected because it didn't handle continuous files. I was therefore trying to make the code handle those files. It seems I am able to read continuous files: https://gist.github.com/Edouard2laire/d96006297a4a854b96d42703b0e3b715#file-process_synchronise_multiples_signals-m-L76-L82 but i am very confused about how to save new continuous files recording into the database. 

Therefore my question is, how to save continuous recordings in the database? 

A simple example is process_nst_mbll in Nirstorm. It can take both continuous recording and imported data but always create imported data:  https://github.com/Nirstorm/nirstorm/blob/master/bst_plugin/mbll/process_nst_mbll.m#L135-L153

How could I change this block of code that saves the output of the process and create a continuous recording if the input of the process was itself a continuous recording? 

Thanks a lot, 
Edouard

**Comment by rcassani** [comment]
@Edouard2laire, can we consider this issue closed?
