### ISSUE TITLE
Possible bug in in_fopen_blackrock.m

### ISSUE THREAD

**Issue by xiaonansun** [brainstorm-tools/brainstorm3#644]
Hello,
Apologies in advance if this is a known issue. [Line 67](https://github.com/brainstorm-tools/brainstorm3/blob/be9102b758aefdddcd2f56d582b4af6cf8e82d15/toolbox/io/in_fopen_blackrock.m#L67) of [in_fopen_blackrock.m](https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/io/in_fopen_blackrock.m) calls for [openNSX.m](https://github.com/BlackrockNeurotech/NPMK/blob/master/NPMK/openNSx.m) with the input `'nozeropad'`, as defined in [Line 63](https://github.com/brainstorm-tools/brainstorm3/blob/be9102b758aefdddcd2f56d582b4af6cf8e82d15/toolbox/io/in_fopen_blackrock.m#L63C1-L64C1). However, openNSX.m has been updated in May 2023 where `'nozeropad'` is now [default](https://github.com/BlackrockNeurotech/NPMK/blob/42f056682dfa77efdc125e24c7cd52410a8772bc/NPMK/openNSx.m#L111C20-L111C24) and will yield an invalid argument.
![image](https://github.com/brainstorm-tools/brainstorm3/assets/42507167/7d5e6350-0989-43dc-9e95-03513a3b8108)
If someone can confirm this is indeed a problem and make the necessary revisions as needed for a future release, that would be greatly appreciated.
Thank you,
Richard

**Comment by rcassani** [comment]
@xiaonansun, thanks for the heads-up.
This now solved at [79e9258](https://github.com/brainstorm-tools/brainstorm3/commit/79e925878bcdb9e6654513fab2f449123f9a23ac)
