### ISSUE TITLE
Loading old database

### ISSUE THREAD

**Issue by Edouard2laire** [brainstorm-tools/brainstorm3#657]
Hello, 

I am contacting you as I am trying to load an old database from a colleague. However, this database was created with an old version of Brainstorm and when I try to load the map I get the following error because sSubject.iFibers and sSubject.iFEM don't exist. WOuld there be an easy way to fix that and load the maps? 

![Screenshot from 2023-11-15 17-01-13](https://github.com/brainstorm-tools/brainstorm3/assets/24530402/f48b2cea-3096-4a0d-b890-087326f95159)

Thanks
Edouard

**Comment by rcassani** [comment]
Have you tried already to regenerate the metadata of the problematic protocol (`protocol.mat`) from the files in HDD?

https://neuroimage.usc.edu/forums/t/brainstorm-database-doesnt-load/36808/2

**Comment by Edouard2laire** [comment]
Ohh it's actually a message I posted haha. I'll try and reopen if it doesn't work :)
