### ISSUE TITLE
Question about connectivity computing with OutputMode 'concat'

### ISSUE THREAD

**Issue by DerfelLee** [brainstorm-tools/brainstorm3#678]
I think there's a mistake in the code about 'concat' but I'm not sure. The variable 'FilesA' is changed to 'FilesA(1)' but the variable 'nFiles', which should be changed to 1, stays the same with no changes. Therefore, the program loops 'nFiles' times calculating the same data over and over again.

![image](https://github.com/brainstorm-tools/brainstorm3/assets/64539337/006810d4-6c27-4bfd-ba55-e1637a15a6a8)

But I'm not sure about this. Please tell me if I'm making a mistake.

Thanks!

**Comment by Moo-Marc** [comment]
I confirm this is a bug.  The solution nFiles = 1 is acceptable, though we might want to keep the number of input files for use in some messages.

**Comment by rcassani** [comment]
Bug fixed in [4144f44](https://github.com/brainstorm-tools/brainstorm3/commit/4144f4416c21165579a90feb5507b57aec2263bb)
