### ISSUE TITLE
Possible bug in importing fieldtrip output?

### ISSUE THREAD

**Issue by Erfan7bt** [brainstorm-tools/brainstorm3#746]
https://github.com/brainstorm-tools/brainstorm3/blob/60fe915bc485de5f60ef5ed275eb6021f080df96/toolbox/io/private/read_fieldtrip_chaninfo.m#L193

I am importing already prepossessed CTF data from the fieldtrip structure, and the only way to import the channel location is by modifying this line of code and applying the unit transformation to all the .Loc column and not just the first as here, otherwise the sensors are 10 times further from the cortex.

this can be seen before the head modeling by "edit channel info" (second loc column 10 times bigger) and after headmodeling when visualizing the Leadfield vectors.

**Comment by rcassani** [comment]
This was in fact a bug. It is now fixed in [a364231](https://github.com/brainstorm-tools/brainstorm3/commit/a3642313c245b1062f95886e76ba832319cab51b)
Thanks @Erfan7bt for reporting it!
