### ISSUE TITLE
Error while opening color chooser

### ISSUE THREAD

**Issue by thomas-vincent** [brainstorm-tools/brainstorm3#79]
I get the following error when I click on "Set surface color":

> Error using matlab.ui.internal.dialog.WebColorChooser/show (line 72)
> Java exception occurred:
> com.mathworks.html.BrowserCreationException:
> com.mathworks.html.BrowserCreationException:
> com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process exited. Exit
> code: 127
> 	at
>         com.mathworks.mlwidgets.html.LightweightBrowserBuilder.buildBrowser(LightweightBrowserBuilder.java:86)
>         	at
>         com.mathworks.mlwidgets.html.LightweightBrowserBuilder.buildDefaultBrowser(LightweightBrowserBuilder.java:52)
>         	at
>         com.mathworks.mlwidgets.html.LightweightBrowserFactory.createLightweightBrowser(LightweightBrowserFactory.java:36)
>         Caused by: com.mathworks.html.BrowserCreationException:
>         com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process
>         exited. Exit code: 127
> 	at
>         com.mathworks.html.jxbrowser.chromium.LightweightChromiumBrowser.<init>(LightweightChromiumBrowser.java:32)
>         	at
>         com.mathworks.mlwidgets.html.LightweightBrowserBuilder.buildBrowser(LightweightBrowserBuilder.java:78)
>         	... 2 more
> Caused by: com.teamdev.jxbrowser.chromium.internal.ipc.IPCException: IPC process
> exited. Exit code: 127
> 	at com.teamdev.jxbrowser.chromium.internal.ipc.d.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 
> Error in uisetcolor_helper>showDialog (line 67)
> ccDialog.show;
> 
> Error in uisetcolor_helper (line 12)
> selectedColor = showDialog(ccDialog);
> 
> Error in uisetcolor (line 33)
> selectedColor = uisetcolor_helper(varargin{:});
> 
> Error in panel_surface>ButtonSurfColorCallback (line 488)
>     colorCortex = uisetcolor(TessInfo(iSurface).AnatomyColor(2,:), 'Select surface
>     color');

Brainstorm version:  Version: 3.4 (26-Apr-2018), from github
Matlab version: 9.2.0.556344 (R2017a)
OS: ubuntu 17.10

Seems like it's coming from jxbrowser so I tried to use another html engine in matlab:
> webutils.htmlrenderer('basic')

But no success, still same error...

**Comment by ftadel** [comment]
Any update?

**Comment by ftadel** [comment]
@thomas-vincent I guess this is not an issue anymore then.
