### ISSUE TITLE
Add DICOM as export format for MRIs

### ISSUE THREAD

**Issue by jeremymoreau** [brainstorm-tools/brainstorm3#82]
Some programs only support DICOM input, and it would therefore be useful to be able to save MRIs (and overlays, via right click ->Snapshot -> Save overlay as MRI) as DICOMs directly from Brainstorm.

There is a built in Matlab function for writing DICOMs (Introduced before R2006a, but requires Image Processing Toolbox): https://www.mathworks.com/help/images/ref/dicomwrite.html
https://www.mathworks.com/help/images/create-new-dicom-series.html

I also found this GPL licenced toolbox, but it was designed with radiotherapy in mind: https://github.com/mwgeurts/dicom_tools

**Comment by ftadel** [comment]
@martcous : Interested in trying working on this with Jeremy?
