### ISSUE TITLE
IO: Add support for reading XDF files

### ISSUE THREAD

**Issue by martcous** [brainstorm-tools/brainstorm3#84]
Fieldtrip already supports it. Sylvain will contact collaborators for example files.

**Comment by ftadel** [comment]
https://github.com/sccn/xdf/wiki/Specifications

**Comment by ftadel** [comment]
@sbaillet you were supposed to get example files?

**Comment by sbaillet** [comment]
Nope.

**Comment by juangpc** [comment]
I've come across this example file. Hope it helps.
https://github.com/sccn/xdf/blob/master/xdf_sample.xdf

**Comment by ftadel** [comment]
https://github.com/sccn/xdf

**Comment by ftadel** [comment]
Finally coded here: https://github.com/brainstorm-tools/brainstorm3/commit/97b9386567aec56fc4fe12eabc46c0ebdd907ae4
