### ISSUE TITLE
Do not save link files in protocol.mat

### ISSUE THREAD

**Issue by martcous** [brainstorm-tools/brainstorm3#86]
Once sources are computed, the size of protocol.mat essentially doubles because every data file has a link added as a child. These could be computed on the fly instead.

**Comment by martcous** [comment]
I am not sure this is a good idea as data links can have children objects (e.g. PSD).

**Comment by ftadel** [comment]
Indeed. The links still have to exist in the database when loaded.
But they can always be regenerated with db_links. So maybe there is no need to save them on the hard drive? I haven't looked at how I did this for years, so I'm not sure how feasible this is, or whether it would really improve the protocol.mat saving time.
