### ISSUE TITLE
OpenMEEG: cortex vertices outside of the inner skull

### ISSUE THREAD

**Issue by ftadel** [brainstorm-tools/brainstorm3#89]
OpenMEEG was recently upgraded from version 2.2 to 2.4: https://github.com/brainstorm-tools/brainstorm3/commit/c6a153be035fbfada114b0597046c987ef604fba#diff-9e590703ce3a61a47c365d821b1164e6

The two versions handle differently the dipoles that are outside of the inner skull surface. In 2.2 it led to incorrect values in the gain matrix, in 2.4 these values are set to zero. 

Until now, we were adjusting the BEM layers (inner skull, outer skull, scalp) so that they include all the vertices, but I disabled some of these constrains because it was altering too much the shape the skull. If we want to get rid of all these outliers, we need to adjust the position of the vertices and project them back inside the skull. This would change our workflow, as now the cortex surfaces are never modified after being imported from FreeSurfer/BrainVISA.

So we have two options:
1) We modify the surfaces, but this require changes in various places in the code, and we need to discuss to define at what point in the workflow we should do this (computation of the BEM layers, computation of OpenMEEG...)
2) We keep it this way and lose a few dipoles in our model (eg. 12 vertices in the epilepsy tutorial). Now OpenMEEG checks for these irregularities correctly. However, Maureen mentioned it could cause some issues in the weighted minimum norm to have columns of the leadfield entirely set to zero.

John, Sylvain: Could you share your point view on this problem?
Thanks

**Comment by ftadel** [comment]
Testing for cortex vertices outside of the inner skull surface is easy:
iVertOut = find(~inpolyhd(cortex.Vertices, inner.Vertices, inner.Faces))

**Comment by agramfort** [comment]
FYI in MNE to deal with this we ignore the outside dipoles.
We can do this as the original source space and the forward source spaces
are not the same.
It can be a subset of the original source space.

HTH

**Comment by ftadel** [comment]
This is already tested for: 
https://github.com/brainstorm-tools/brainstorm3/blob/master/toolbox/forward/bst_openmeeg.m#L147
