### ISSUE TITLE
Enlarge left panel of Montage Editor

### ISSUE THREAD

**Issue by martcous** [brainstorm-tools/brainstorm3#97]
Right now, with SEEG montages that have very long channel names, the left panel of the Montage Editor is too small to properly read them and their keyboard shortcut. Consider enlarging its fixed width or even making it extendable.

**Comment by ftadel** [comment]
Split panels are annoying for lots of reason. Now I always prefer static solutions when possible.
A larger static width would do the job. Or something that adjusts automatically to the longest element in the list if you're looking for fun with the cell renderers :)

**Comment by martcous** [comment]
Done in https://github.com/brainstorm-tools/brainstorm3/commit/767a593bb57b33325cb1a3de9b4f09330b0f3a65.
